// theme constant
export const gridSpacing = 3;
export const drawerWidth = 260;
export const appDrawerWidth = 320;

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const GET_LOGGED_IN_USER_REQUEST = 'GET_LOGGED_IN_USER_REQUEST';
export const GET_LOGGED_IN_USER_SUCCESS = 'GET_LOGGED_IN_USER_SUCCESS';
export const GET_LOGGED_IN_USER_FAIL = 'GET_LOGGED_IN_USER_FAIL';

export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL';

export const GET_GLO_DATA_PLAN_REQUEST = 'GET_GLO_DATA_PLAN_REQUEST';
export const GET_GLO_DATA_PLAN_SUCCESS = 'GET_GLO_DATA_PLAN_SUCCESS';
export const GET_GLO_DATA_PLAN_FAIL = 'GET_GLO_DATA_PLAN_FAIL';

export const GET_MTN_DATA_PLAN_REQUEST = 'GET_MTN_DATA_PLAN_REQUEST';
export const GET_MTN_DATA_PLAN_SUCCESS = 'GET_MTN_DATA_PLAN_SUCCESS';
export const GET_MTN_DATA_PLAN_FAIL = 'GET_MTN_DATA_PLAN_FAIL';

export const GET_AIRTEL_DATA_PLAN_REQUEST = 'GET_AIRTEL_DATA_PLAN_REQUEST';
export const GET_AIRTEL_DATA_PLAN_SUCCESS = 'GET_AIRTEL_DATA_PLAN_SUCCESS';
export const GET_AIRTEL_DATA_PLAN_FAIL = 'GET_AIRTEL_DATA_PLAN_FAIL';

export const BUY_AIRTIME_REQUEST = 'BUY_AIRTIME_REQUEST';
export const BUY_AIRTIME_SUCCESS = 'BUY_AIRTIME_SUCCESS';
export const BUY_AIRTIME_FAIL = 'BUY_AIRTIME_FAIL';

export const BUY_DATA_REQUEST = 'BUY_DATA_REQUEST';
export const BUY_DATA_SUCCESS = 'BUY_DATA_SUCCESS';
export const BUY_DATA_FAIL = 'BUY_DATA_FAIL';

export const FUND_WALLET_BY_MONNIFY_REQUEST = 'FUND_WALLET_BY_MONNIFY_REQUEST';
export const FUND_WALLET_BY_MONNIFY_SUCCESS = 'FUND_WALLET_BY_MONNIFY_SUCCESS';
export const FUND_WALLET_BY_MONNIFY_FAIL = 'FUND_WALLET_BY_MONNIFY_FAIL';


